backend:
  name: github
  branch: main
  repo: 'cswitenky/cswitenky'
  base_url: https://decap.switenky.com
  auth_endpoint: auth

site_url: https://switenky.com

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: public/images
public_folder: /images

collections:
  - name: 'posts'
    label: 'Blog Posts'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'YYYY-MM-DD',
          time_format: false,
        }
      - {
          label: 'Draft',
          name: 'draft',
          widget: 'boolean',
          default: false,
          required: false,
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          modes: ['raw', 'rich_text'],
          default_mode: 'raw',
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'content/pages/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', default: 'Home' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - {
              label: 'Content',
              name: 'body',
              widget: 'markdown',
              required: false,
              modes: ['raw', 'rich_text'],
              default_mode: 'raw',
            }
